let moves = [
    {
        "5L": {
            "damage": 400,
            "type": 2,
            "numberOfHits": null,
            "minimumDamage": null,
            "scalingIncrement": null,
        },
        "5LL": {
            "damage": 700,
            "type": 1,
            "numberOfHits": null,
            "minimumDamage": null,
            "scalingIncrement": null,
        },
        "5LLL": {
            "damage": 1000,
            "type": 1,
            "numberOfHits": null,
            "minimumDamage": null,
            "scalingIncrement": null,
        },
        "2L": {
            "damage": 400,
            "type": 2,
            "numberOfHits": null,
            "minimumDamage": null,
            "scalingIncrement": null,
        },
        "5M": {
            "damage": 700,
            "type": 1,
            "numberOfHits": null,
            "minimumDamage": null,
            "scalingIncrement": null,
        },
        "2M" : {
            "damage" : 700,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "6M" : {
            "damage" : 850,
            "type" : 3,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "5H" : {
            "damage" : 850,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "2H" : {
            "damage" : 850,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "2S(1)" : {
            "damage" : 600,
            "type" : 2,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "2S(2)" : {
            "damage" : 700,
            "type" : 2,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "JL" : {
            "damage" : 400,
            "type" : 2,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "JM" : {
            "damage" : 700,
            "type" : 2,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "JH" : {
            "damage" : 850,
            "type" : 2,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "J2H" : {
            "damage" : 850,
            "type" : 2,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "JS" : {
            "damage" : 400,
            "type" : 2,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "J2S(1)" : {
            "damage" : 600,
            "type" : 2,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "J2S(2)" : {
            "damage" : 700,
            "type" : 2,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "236L(1)" : {
            "damage" : 500,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "236L(2)" : {
            "damage" : 700,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "236M(1)" : {
            "damage" : 500,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "236M(2)" : {
            "damage" : 700,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "236H(1)" : {
            "damage" : 300,
            "type" : 2,
            "numberOfHits" : 4,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "236H(2)" : {
            "damage" : 700,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "214L" : {
            "damage" : 1000,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "214M" : {
            "damage" : 1350,
            "type" : 3,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "214H(1)" : {
            "damage" : 1000,
            "type" : 3,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "214H(2)" : {
            "damage" : 200,
            "type" : 3,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "J236L" : {
            "damage" : 350,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "J236M(1)" : {
            "damage" : 80,
            "type" : 1,
            "numberOfHits" : 7,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "J236M(2)" : {
            "damage" : 600,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : 0,
        },
        "J236H(1)" : {
            "damage" : 80,
            "type" : 1,
            "numberOfHits" : 13,
            "minimumDamage" : null,
            "scalingIncrement" : null,
        },
        "J236H(2)" : {
            "damage" : 900,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : 0,
        },
        "LVL1(TOHAN)" : {
            "damage" : 340,
            "type" : 1,
            "numberOfHits" : 10,
            "minimumDamage" : 910,
            "scalingIncrement" : null,
        },
        "LVL3(TOHAN)" : {
            "damage" : 230,
            "type" : 1,
            "numberOfHits" : 20,
            "minimumDamage" : 1740,
            "scalingIncrement" : null,
        },
        "LVL5(TOHAN)" : {
            "damage" : 110,
            "type" : 1,
            "numberOfHits" : 20,
            "minimumDamage" : 1100,
            "scalingIncrement" : null,
        },
        "DR(START)" : {
            "damage" : 1100,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : 8,
        },
        "DR(COMBO)" : {
            "damage" : 1460,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : 8,
        },
        "SD" : {
            "damage" : 300,
            "type" : 2,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : 8,
        },
        "V" : {
            "damage" : 850,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : 170,
            "scalingIncrement" : 5,
        },
        "$" : {
            "damage" : 0,
            "type" : 3,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : 1,
        },
        "BASEKU" : {
            "damage" : 800,
            "type" : 2,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : 2,
        },
        "LVL1(BASEKU)" : {
            "damage" : 2320,
            "type" : 2,
            "numberOfHits" : null,
            "minimumDamage" : 783,
            "scalingIncrement" : null,
        },
        "LVL3(BASEKU)" : {
            "damage" : 5605,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : 1985,
            "scalingIncrement" : null,
        },
        "SSJGOKU" : {
            "damage" : 200,
            "type" : 2,
            "numberOfHits" : 5,
            "minimumDamage" : null,
            "scalingIncrement" : 2,
        },
        "LVL1(SSJGOKU)(STRAIGHT)" : {
            "damage" : 250,
            "type" : 2,
            "numberOfHits" : 10,
            "minimumDamage" : 750,
            "scalingIncrement" : null,
        },
        "LVL1(SSJGOKU)(DIAGONAL)" : {
            "damage" : 270,
            "type" : 2,
            "numberOfHits" : 10,
            "minimumDamage" : 810,
            "scalingIncrement" : null,
        },
        "LVL3(SSJGOKU)" : {
            "damage" : 4208,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : 1759,
            "scalingIncrement" : null,
        },
        "TIEN" : {
            "damage" : 800,
            "type" : 2,
            "numberOfHits" : null,
            "minimumDamage" : null,
            "scalingIncrement" : 2,
        },
        "LVL1(TIEN)" : {
            "damage" : 2400,
            "type" : 2,
            "numberOfHits" : null,
            "minimumDamage" : 1032,
            "scalingIncrement" : null,
        },
        "LVL1+1(TIEN)" : {
            "damage" : 3058,
            "type" : 2,
            "numberOfHits" : null,
            "minimumDamage" : 1426,
            "scalingIncrement" : null,
        },
        "LVL3(TIEN)" : {
            "damage" : 3600,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : 1872,
            "scalingIncrement" : null,
        },
        "LVL3+1(TIEN)" : {
            "damage" : 900,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : 600,
            "scalingIncrement" : null,
        },
        "LVL3+2(TIEN)" : {
            "damage" : 800,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : 600,
            "scalingIncrement" : null,
        },
        "LVL3+3(TIEN)" : {
            "damage" : 700,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : 600,
            "scalingIncrement" : null,
        },
        "LVL3+4(TIEN)" : {
            "damage" : 600,
            "type" : 1,
            "numberOfHits" : null,
            "minimumDamage" : 600,
            "scalingIncrement" : null,
        },
    }];